[package]
name = "tokenizer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
regex = "1.10"

[dev-dependencies]
proptest = "1.4"
criterion.workspace = true
serde_json = "1.0"

[[bench]]
name = "tokenizer_bench"
harness = false
