[package]
name = "vector"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
proptest = "1.4"
criterion.workspace = true

[[bench]]
name = "vector_bench"
harness = false
